# Preprocessing: remove stopwords, lower-case all, remove diacritics, remove punctuation
# Vector-Space:  MDS with angular differences between PPMI-Weighted BoWs of all Terms (dimensions 20, 50, 100, 200)
# Candidates:    Frequent Nouns, Adjectives, Nounphrases, Adjectivephrases (doc-freq >= 100 for movies-dataset)
# Cand-Filter:   binary linear SVM with pos/neg-count-ratio as instance cost, then select all for which kappa(svm_rank, count(t,e)) >= 0.1
# Cand-Merging:  Custom

pp_components:                mfautcsdp
translate_policy:             translate
quantification_measure:       ppmi
dissim_measure:               norm_ang_dist
embed_algo:                   "mds"
embed_dimensions:             [20, 50, 100, 200]
extraction_method:            pp_keybert
#TODO: DESC15 hat darauf abgezielt ~22k keywords zu haben => mit meinen params dafür sorgen dass ich auch auf sowas komme, mit den aktuellen ists nur 2402!
#candidate_min_term_count:     25 #movies has samples-to-threshold value of 100, placetypes has 35, 20newsgrups has 614, so for 8000 courses any threshold from 2 to 25 seems reasonable (BUT see above, I get too little)!!
#TODO this should be part of the dataset-config!
max_ngram:                    5                   # not explicitly, but it takes adjective phrases so it's something >=3
dcm_quant_measure:            count

# classifier_succmetric:        [kappa_count2rank_onlypos, kappa_rank2rank_onlypos_min]  #unclear if the ranking induced by count, or the baremetal count
# TODO add back as soon as clusters work #PRECOMMIT #FIXPRECOMMIT
prim_lambda:                  0.5
sec_lambda:                   0.1
__perdataset__:
  placetypes:
    extraction_method: "all" #in the placetypes-dataset, ALL words are candidates (21.8k)

#TODO alles ab cand-filter fehlt noch...

